# Generated by Django 4.2.7 on 2025-09-19 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="KPIReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "period",
                    models.CharField(
                        choices=[("weekly", "Weekly"), ("monthly", "Monthly")],
                        max_length=20,
                    ),
                ),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                ("tickets_received", models.PositiveIntegerField(default=0)),
                ("tickets_reopened", models.PositiveIntegerField(default=0)),
                ("tickets_resolved", models.PositiveIntegerField(default=0)),
                ("tickets_unresolved", models.PositiveIntegerField(default=0)),
                ("tickets_still_open", models.PositiveIntegerField(default=0)),
                ("first_reply_time_avg", models.DurationField(blank=True, null=True)),
                ("resolution_time_avg", models.DurationField(blank=True, null=True)),
                (
                    "csat",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("refunds", models.PositiveIntegerField(default=0)),
                ("chargebacks_opened", models.PositiveIntegerField(default=0)),
                ("chargebacks_processed", models.PositiveIntegerField(default=0)),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tag",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("faulty_items", "Faulty Items"),
                            ("delivery_status", "Delivery Status"),
                            ("missing_items", "Missing Items"),
                            ("return_refund", "Return & Refund"),
                            ("infos_requested", "Infos Request"),
                            ("claim_out_of_period", "Claim Out of Period"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "tag_details",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kpi_reports",
                        to="accounts.client",
                    ),
                ),
            ],
            options={
                "ordering": ["-period_start"],
                "unique_together": {("client", "period", "period_start", "period_end")},
            },
        ),
    ]
