# Generated by Django 4.2.7 on 2025-09-23 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="kpireport",
            old_name="first_reply_time_avg",
            new_name="first_response_time_avg",
        ),
        migrations.RenameField(
            model_name="kpireport",
            old_name="refunds",
            new_name="total_refund_requests",
        ),
        migrations.RemoveField(
            model_name="kpireport",
            name="csat",
        ),
        migrations.RemoveField(
            model_name="kpireport",
            name="tag",
        ),
        migrations.RemoveField(
            model_name="kpireport",
            name="tag_details",
        ),
        migrations.AddField(
            model_name="kpireport",
            name="areas_for_improvement",
            field=models.JSONField(
                blank=True, default=list, help_text="List of areas needing improvement"
            ),
        ),
        migrations.AddField(
            model_name="kpireport",
            name="challenges_faced",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="kpireport",
            name="common_requests",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="JSON object with request types and counts",
            ),
        ),
        migrations.AddField(
            model_name="kpireport",
            name="first_response_sla_percentage",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Percentage of inquiries responded to within SLA",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="kpireport",
            name="positive_trends",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of positive observations with counts",
            ),
        ),
        migrations.AddField(
            model_name="kpireport",
            name="refund_replacement_requests",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="JSON object with refund/replacement types and counts",
            ),
        ),
        migrations.AddField(
            model_name="kpireport",
            name="resolution_48h_percentage",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Percentage of tickets resolved within 48 hours",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="kpireport",
            name="shop_name",
            field=models.CharField(
                blank=True, help_text="e.g., Pridola UK", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="kpireport",
            name="slack_channel",
            field=models.CharField(
                blank=True, default="#customer-service-weekly-update", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="kpireport",
            name="tickets_received",
            field=models.PositiveIntegerField(
                default=0, help_text="Total support tickets opened"
            ),
        ),
        migrations.AlterField(
            model_name="kpireport",
            name="tickets_resolved",
            field=models.PositiveIntegerField(
                default=0, help_text="Total inquiries resolved"
            ),
        ),
        migrations.AlterField(
            model_name="kpireport",
            name="tickets_still_open",
            field=models.PositiveIntegerField(
                default=0, help_text="Total tickets still open"
            ),
        ),
        migrations.CreateModel(
            name="WeeklyHighlight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "highlight_type",
                    models.CharField(
                        choices=[
                            ("common_request", "Most Common Request"),
                            ("positive_trend", "Positive Trend"),
                            ("improvement_area", "Area for Improvement"),
                            ("challenge", "Challenge Faced"),
                            ("observation", "General Observation"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "count",
                    models.PositiveIntegerField(
                        blank=True, help_text="Number of cases if applicable", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="highlights",
                        to="dashboard.kpireport",
                    ),
                ),
            ],
            options={
                "ordering": ["highlight_type", "title"],
            },
        ),
        migrations.CreateModel(
            name="TicketCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tag",
                    models.CharField(
                        choices=[
                            ("faulty_items", "Faulty Items"),
                            ("delivery_status", "Delivery Status"),
                            ("missing_items", "Missing Items"),
                            ("return_refund", "Return & Refund"),
                            ("infos_requested", "Infos Request"),
                            ("claim_out_of_period", "Claim Out of Period"),
                        ],
                        max_length=50,
                    ),
                ),
                ("tag_detail", models.CharField(max_length=200)),
                ("cases_count", models.PositiveIntegerField(default=0)),
                (
                    "percentage",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ticket_categories",
                        to="dashboard.kpireport",
                    ),
                ),
            ],
            options={
                "ordering": ["tag", "tag_detail"],
            },
        ),
    ]
